### PR TITLE
Add Wasabi Wallet backup guide

### PR DESCRIPTION
**Pull request by MaxHillebrand**
I tried to follow the writing convention for the existing guides.

### CODE REVIEW

**Comment by openoms** [comment]
Thanks for this. I just need to test before merging.
Should we add the `Wasabi Wallet password` to the instances of:
`* Password to laptop / disk encryption` ?

**Comment by MaxHillebrand** [comment]
The `Wasabi Wallet password` is the `(BIP39) Passphrase`. You need to write it every time you want to spend a coin, it decrypts the master private key.

**Comment by openoms** [comment]
> The `Wasabi Wallet password` is the `(BIP39) Passphrase`. You need to write it every time you want to spend a coin, it decrypts the master private key.

Thanks that was not clear for (hence the need to test), but then you would need the Passphrase in package 3 as well (instead of the seed) to be able to recover with the combination of any two packages.

**Comment by openoms** [comment]
Actually because the same passphrase is the part of all 3 full backup packages this scheme does not work with the Wasabi Wallet.
It needs at least two completely independent ways to restore/spend the funds.

**Pull request closed without merging**
