### PR TITLE
add "A private flow through JoinMarket" guide

### PR DESCRIPTION
**Pull request by openoms**
For initial review.
All comments and suggestions are welcome.

### CODE REVIEW

**Comment by chris-belcher** [comment]
I'd add a paragraph at the start that "hooks" the reader and immediately tells them what the rest of the document is about. So that someone who reads things fast can look at the first two sentences and immediately know that this document is about bitcoin, privacy, an introduction for newbs, joinmarket, and learning some of the terminology.

In the part where you define "maker" and "taker", it might be worth adding that the silent word is "market" or "liquidity". So "liquidity taker" or "market taker". It might make the words and concept more understandable to people.

The "Leaving the JoinMarket wallet" should mention that it only applies to the yield-generator, because with tumbler your funds leave automatically.

I'd separate the document into clear sections between using tumbler, and using yield generator. Most users should use tumbler I think. Today there's common advice to try to mix the roles of taker and maker, which IMO isn't _wrong_, but just not realistic because a maker gets coinjoins so rarely if they don't have valuable fidelity bonds. Yield-generators are more like service providers. If you imagine a bitcoin user as someone who wants to use bitcoin's privacy properties (e.g. buying an anonymous VPS, donating to something privately, etc) then they need to use their coins fairly quickly, not wait around for weeks to get coinjoins.

Also I think it's worth adding advice that one single coinjoin doesn't improve privacy much, and anyone wanting to improve privacy needs to run tumbler (or possibly yield-generator).

I know these last two points might be a bit controversial, we had a little debate on this issue: https://github.com/JoinMarket-Org/joinmarket-clientserver/issues/1047

**Comment by openoms** [comment]
@chris-belcher thank you for the detailed comment, will make changes.

Agree that the Tumbler should be recommended more. My hold off is the potentially very high fee burden of sending ~10 multiple kilobyte size transactions (+ paying the Maker fees).
Privacy has a cost, but it would make sense only for at least multiple million sats and even then a significant part would go towards the fees.

What do you think a sensible minimum amount (ballpark) recommendation would be to use the Tumbler?

**Comment by openoms** [comment]
The question of fees and recommended amounts for the Tumbler are addressed in ;https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/master/docs/tumblerguide.md#a-note-on-fees

**Comment by chris-belcher** [comment]
> What do you think a sensible minimum amount (ballpark) recommendation would be to use the Tumbler?

I don't know sorry

**Comment by openoms** [comment]
Merging this now, but further comments, suggestion and PRs are very welcome.

**Pull request merged**
